'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class 博客系统资源
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("走過去的全家桶.博客系统资源", GetType(博客系统资源).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 body {
        '''    font-family: Consolas, &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Noto Sans SC&quot;, &quot;Microsoft Yahei&quot;, Tahoma, Arial, sans-serif;
        '''    font-size: 1em;
        '''    background-image: url(&apos;/bg.jpg&apos;);
        '''    background-position: center;
        '''    background-repeat: no-repeat;
        '''    background-size: cover;
        '''    background-attachment: fixed;
        '''    line-height: 1.4;
        '''}
        '''
        '''header,
        '''section,
        '''footer,
        '''aside,
        '''nav,
        '''main,
        '''article,
        '''figure {
        '''    display: block;
        '''}
        '''
        '''a {
        '''    text-decoration: none;
        '''    color: #dfebf5;
        '''}
        '''
        '''a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property css() As String
            Get
                Return ResourceManager.GetString("css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;meta charset=&apos;UTF-8&apos;&gt;
        '''&lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        '''&lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;ie=edge&apos;&gt;
        '''&lt;link rel=&apos;icon&apos; href=&apos;/favicon.ico&apos;&gt;
        '''&lt;link rel=&apos;stylesheet&apos; href=&apos;https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css&apos;&gt;
        '''&lt;link rel=&apos;stylesheet&apos; href=&apos;/maincss.css&apos;&gt; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property head() As String
            Get
                Return ResourceManager.GetString("head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;h1&gt;
        '''Gordon Walkedby&apos;s Blog&lt;br&gt;
        '''戈登走過去的博客
        '''&lt;/h1&gt;
        '''&lt;nav&gt;
        '''
        '''&lt;div class=&apos;nav-t&apos;&gt; &lt;a href=&apos;/&apos;&gt;首页&lt;/a&gt;&lt;/div&gt;
        '''
        '''&lt;div class=&apos;nav-t&apos;&gt; &lt;a href=&apos;/p0/&apos;&gt;文章列表&lt;/a&gt;&lt;/div&gt;
        '''
        '''&lt;div class=&apos;nav-t&apos;&gt;
        '''    &lt;a href=&apos;#&apos;&gt;社交媒体&lt;/a&gt;
        '''    &lt;ul&gt;
        '''        &lt;li&gt;&lt;a href=&apos;https://weibo.com/gordon2001&apos;&gt;微博&lt;/a&gt;&lt;/li&gt;
        '''        &lt;li&gt;&lt;a href=&apos;https://twitter.com/GordonWalkedby&apos;&gt;Twitter&lt;/a&gt;&lt;/li&gt;
        '''        &lt;li&gt;&lt;a href=&apos;https://space.bilibili.com/4523834/#/&apos;&gt;bilibili&lt;/a&gt;&lt;/li&gt;
        '''        &lt;li&gt;&lt;a href=&apos;https://steamcommunity.com/profiles/76561198099466387/m [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property header() As String
            Get
                Return ResourceManager.GetString("header", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
